/ping ハンドラーの追加
mahiro72/go-simple-echo-server pull request #1
Opened 2023-01-16 17:31 UTC by mahiro72

2023-01-23 04:50 UTC, mokoshin0720 requested changes
Routerの自作など抽象度が高めの実装お疲れさまでした🙌🏻
ispecのコード規約やgo<->jsonのやり取り部分などについてコメントさせてもらいました！
コメントの意図が掴みづらい部分などあれば、お気軽にお声がけください〜

2023-01-23 04:50 UTC, mokoshin0720 commented on src/presentation/http/router/router.go
> +	// middlewareの設定
ispecではコメントがなくても理解できるコードを目指しているため、なるべくコードにコメントは残さず実装をする方針で進めています！(よっぽど複雑な処理を行う場合は、notion上にドキュメントを書いてリンクを貼るなどして対応しています。)

今回、自分の学習用としてコメントを残しているのであればそのままでOKですが、そうでない場合は「r.setMiddleware()」でmiddlewareの設定を行っていることは理解できるので削除しちゃっても良いかなと思いました🙆🏻‍♂️

2023-01-23 04:50 UTC, mokoshin0720 commented on src/presentation/http/handlers/health.go
> +	res := map[string]interface{}{
goでjsonを扱う場合は、[structを宣言して型変換を行う](https://zenn.dev/hsaki/articles/go-convert-json-struct#go%E3%81%A7%E8%A1%8C%E3%81%86%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89%E3%83%BB%E3%83%87%E3%82%B3%E3%83%BC%E3%83%89)方がjsonに入る値が明確になり、フロントエンドとのやり取りでのバグが生じづらくなるので良いかなと思いました！(今回の実装だと、`map[string]interface{}`を使っていただいているので`message`以外の値が容易に入れられたり、実装者以外の人から見ると何を返したいAPIなのかが一目でわかりづらくなってしまう恐れがあるかなと)

2023-01-23 04:50 UTC, mokoshin0720 commented on src/presentation/http/response/response.go
> +func WriteJson(w http.ResponseWriter, v any, status int) {
`any`を使わない方が安全性は高くなると思うので基本的に開発中は使わないのですが、`WriteJson`はアプリケーション全体で汎用的に使われるコードを想定していると思うので、今回は`any`で適切かなと思いました🙆🏻‍♂️

1点細かい部分だと、`v`に入る値は実際にはレスポンスとなると思うので、`res`や`resp`などの命名の方が分かりやすそうかなと、、！

2023-01-23 04:50 UTC, mokoshin0720 commented on src/presentation/http/router/router.go
> +package router
今回は自作のRouterを作成することで抽象度を上げて実装をしていただいたと思うのですが、go-chiをそのまま使う形だとかなりシンプルに実装が出来るので、(すでに見られているかもですが)[参考](https://qiita.com/minoritea/items/afaf10de3c5b6ebafa84#chi%E3%81%AE%E5%88%A9%E7%94%A8)を載せておきます！

2023-02-01 00:10 UTC, mahiro72 commented on src/presentation/http/router/router.go
> +	// middlewareの設定
リンクを貼る対応、承知いたしました！
確認ありがとうございます

2023-02-01 00:23 UTC, mahiro72 commented on src/presentation/http/handlers/health.go
> +	res := map[string]interface{}{
記事の共有ありがとうございます！

Encoderとmarshalの違いをいまいち理解してなかったので大変参考になりました。

2023-02-01 00:28 UTC, mahiro72 commented on src/presentation/http/response/response.go
> +func WriteJson(w http.ResponseWriter, v any, status int) {
anyの扱い方について、承知いたしました！
自分もおっしゃる通りだと思うので、基本的には使わないようにします。

命名の件も承知いたしました！

2023-02-01 00:30 UTC, mahiro72 commented on src/presentation/http/router/router.go
> +package router
共有ありがとうございます！

今回、httpの層でgo-chiから他のライブラリに移行する場合を想定して抽象化しておりましたが、
今回の課題ではそこまで実装する必要がなかったかなと思いました！

参考も共有していただきありがとうございます🙇

2023-02-01 00:47 UTC, mahiro72 commented on src/presentation/http/router/router.go
> +	// middlewareの設定
[del:comment](https://github.com/mahiro72/go-simple-echo-server/pull/1/commits/cb3095a9a2a29ee32277d0666f04627853ae5b8d)

2023-02-01 00:48 UTC, mahiro72 commented on src/presentation/http/handlers/health.go
> +	res := map[string]interface{}{
[map[string]interface{}の削除](https://github.com/mahiro72/go-simple-echo-server/pull/1/commits/5d96705acbf19875e4407469ebb89c4d20d4a734)

2023-02-01 00:48 UTC, mahiro72 commented on src/presentation/http/response/response.go
> +func WriteJson(w http.ResponseWriter, v any, status int) {
[fix: argname](https://github.com/mahiro72/go-simple-echo-server/pull/1/commits/daec5aa77753a67da2226152800b4ae1ef10ca07)

2023-02-02 04:35 UTC, yamad07 commented on src/presentation/http/response/response.go
> +func WriteJson(w http.ResponseWriter, res any, status int) {
`WriteJSON`

2023-02-02 04:35 UTC, yamad07 commented on src/presentation/http/response/response.go
> +func WriteJson(w http.ResponseWriter, res any, status int) {
Goでは略称は全部大文字で書くことが多い

2023-02-10 10:01 UTC, merged